version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_lb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
    restart: always

  app:
    build: ./app
    deploy:
      replicas: 3
    volumes:
      - /change/to/your/local/path/Whist/logs/app_logs:/var/log # Mount your local logs folder
    restart: always

  db:
    build: ./db
    volumes:
      - /change/to/your/local/path/Whist/logs/db_data:/var/lib/mysql # Mount your local logs folder
      - /change/to/your/local/path//Whist/logs/db_logs:/var/log/mysql # Mount your local logs folder
    restart: always

volumes:
  app_logs:
  db_data:
  db_logs:  

