events {}

http {
    resolver 127.0.0.11 valid=10s;  # Use Docker's internal DNS resolver

    map $cookie_internal_ip $backend {
        default "app_cluster";  # Default to load balancing
        ~^(?<ip>\d+\.\d+\.\d+\.\d+)$ "$ip:5000";  # Extract IP directly
    }

    upstream app_cluster {
        zone backend 64k;
        server app:5000 resolve;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://$backend;  # Use extracted IP

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}

