events {}

http {
    upstream app_cluster {
        hash $cookie_session_id consistent;  # Use consistent hashing on the session cookie
        server whist-app-1:5000;
        server whist-app-2:5000;
        server whist-app-3:5000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app_cluster;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_cookie_path / "/; HttpOnly; Secure; Max-Age=300";
            add_header Set-Cookie "session_id=$remote_addr; Path=/; Max-Age=300; HttpOnly";  # Use client IP as a session ID
        }
    }
}

