events {}

http {
    upstream app_cluster {
        server app:5000;  # Points to the app service
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app_cluster;
        }
    }
}

